/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    Library functionTest =new Library();
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

@Test public void rollTest(){
int n=4;
        assertEquals(n , functionTest.roll(n).size());
//    assertEquals(6 , testing.roll(n).size());
}


    @Test public void duplicateTest(){
assertTrue(functionTest.containsDuplicates(new int[]{4,5,5,4,6}));

    }

    @Test public void avgData(){

        assertEquals(5,functionTest.arrayOfNumber(new int[]{5,5,5,5,5}));
    }
}
