/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.*;
import java.util.ArrayList;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }


    public static void main(String[] args){
System.out.println("The array of dice roll is : " + roll(6) );
int[] array={4,5,6,5,};
        System.out.println("The array contains duplicate values : " + containsDuplicates(array));
   int[] number= {1,3,4,5,3,6};
        System.out.println("Average value of the array elements is : " + arrayOfNumber(number));


        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        System.out.println("Minimum avg array " + Arrays.toString(minAvgArray(weeklyMonthTemperatures)));

    }


    public  static ArrayList roll(int n){
        ArrayList<Integer> diceArray=new ArrayList<Integer>();
        int max=6;
        int min =1;

        for (int i = 0; i < n; i++){
            int random=(int) (Math.random() * (max-min))+1;
            diceArray.add(random);
        }
        return diceArray;
    }


    public static boolean containsDuplicates(int[] array){
        for (int i = 0; i < array.length; i++) {
            for (int j = 0; j < array.length; j++) {
                if (i != j ){
                    if (array[i] == array[j]){
                        return true;
                    }
                }
            }
        }
        return false;
    }
    public static double arrayOfNumber(int[] number){

        double average=0;
        //calculate sum of all array elements
        int sum = 0;

        for (int i : number) {
            sum += i;
        }

        //calculate average value
         average =(double) sum / number.length;
        return average;

    }

    public static int[] minAvgArray(int[][] array){
        int[] otherArray = array[0];
        for (int[] i : array) {
            if (arrayOfNumber(i) < arrayOfNumber(otherArray)) {
                otherArray = i;
            }


        }
        return otherArray;
    }





}
