/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {


        Restaurant restaurant = new Restaurant("Mac" , 5,5);
        System.out.println(restaurant);


        Review firstReview = new Review("good","Mosa",5);
        Review secondReview = new Review("good","Ahmad",4);

        restaurant.addReviews(firstReview);
        restaurant.addReviews(secondReview);

        System.out.println(restaurant.getReviews());


    }

}
