/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.nio.file.Paths;

import static linter.App.*;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void testingSplinter(){


        // testing  no errors
        String noErrOut = "";
        Path noErrorFile = Paths.get("src/main/resources/testNoError.js");

        assertEquals(noErrOut,javaScriptLinter(noErrorFile));


        // testing  one error
        String oneErrOut = "Line 3: Missing semicolon.\n";
        Path oneErrorFile = Paths.get("src/main/resources/testOneError.js");

        assertEquals(oneErrOut,javaScriptLinter(oneErrorFile));



        // testing  some error
        String someErrOut = "Line 3: Missing semicolon.\n"+"Line 5: Missing semicolon.\n";
        Path someErrorsFile = Paths.get("src/main/resources/testSomeError.js");

        assertEquals(someErrOut,javaScriptLinter(someErrorsFile));



        // testing  many error
        String manyErrOut = "Line 3: Missing semicolon.\n"+"Line 5: Missing semicolon.\n"+"Line 10: Missing semicolon.\n"+"Line 11: Missing semicolon.\n"+"Line 12: Missing semicolon.\n"+"Line 13: Missing semicolon.\n"+"Line 14: Missing semicolon.\n";
        Path manyErrorsFile = Paths.get("src/main/resources/testManyError.js");

        assertEquals(manyErrOut,javaScriptLinter(manyErrorsFile));



        // testing  empty
        String emptyErrOut = "";
        Path emptyFile = Paths.get("src/main/resources/empty.js");

        assertEquals(emptyErrOut,javaScriptLinter(emptyFile));
    }
}